require 'spec_helper'

describe 'beanstalkd::default' do
  let(:chef_run) do
    ChefSpec::ServerRunner.new(:platform => 'debian', :version => '7.2') do |node|
      node.automatic[:fqdn] = 'myserver'
    end.converge(described_recipe)
  end

  it 'should install beanstalkd service' do
    expect(chef_run).to upgrade_package('beanstalkd')
  end

  it 'should start beanstalkd service' do
    expect(chef_run).to enable_service('beanstalkd')
    expect(chef_run).to start_service('beanstalkd')
  end

  it 'should creates a defaults file at /etc/default/beanstalkd' do
    expect(chef_run).to(render_file('/etc/default/beanstalkd').with_content do |content|
      expect(content).to include('Generated by Chef for myserver')
      expect(content).to include('DAEMON_OPTS="-p 11300 -l 127.0.0.1 "')
    end)
  end
end
